theme: jekyll-theme-cayman
title: "SHIKSHA GUPTA"
name: &name "Shiksha Gupta"
description: &description "DATA ANALYTICS & DATA SCIENCE"
name: &name "Shiksha Gupta"

social:
  type                   : Person
  name                   : Linkedin
  links: https://www.linkedin.com/in/guptashiksha
