theme: jekyll-theme-cayman
title: "SHIKSHA GUPTA"
name: &name "Shiksha Gupta"
description: &description "DATA ANALYTICS & DATA SCIENCE"
name: &name "Shiksha Gupta"

author:
  linkedin: https://www.linkedin.com/in/guptashiksha
