theme: jekyll-theme-cayman
title                    : "SHIKSHA GUPTA"
locale                   : "en-US"
name                     : &name "Shiksha Gupta"
description              : &description "Data Analytics & Data Science"
